
name: create-droplet-digitalocean

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:

#DigitalOcean Data
  DROPLET_NAME: droplet-neurone-trivia-v1 #Nombre que llevará el droplet a crear
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  FINGERPRINT_SSH_KEY_DIGITALOCEAN: "dd:ca:b2:21:ed:6e:47:dd:12:22:58:c2:58:5d:77:e6"
  WORKING_DIRECTORY: ./NEURONE-Trivia-Deployment/terraform-files/digitalocean
  

jobs:
  create-droplet:

    runs-on: ubuntu-22.04

    # strategy:
    #   matrix:
    #     node-version: [16.14.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
     
    - name: Cloning NEURONE-Trivia-Deployment repository.
      uses: actions/checkout@v3
      with:
        repository: trabajo-titulacion-neurone/NEURONE-Trivia-Deployment
        # token: 
        path: NEURONE-Trivia-Deployment

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    # - name: Install doctl
    #   uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform init

    - name: Edit the variables.tf file to add the DigitalOcean token and droplet name
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
      
        # Reemplazar el valor de default en la variable digitalocean_token del archivo variables.tf
        digitalocean_token="${{ env.DIGITALOCEAN_ACCESS_TOKEN }}"
        sed -i '/variable "token_digitalocean" {/,/}/{s/^\(\s*default\s*=\s*"\).*\(".*\)/\1'"$digitalocean_token"'\2/}' variables.tf

        # Reemplazar el valor de default en la variable droplet_name del archivo variables.tf
        droplet_name="${{ env.DROPLET_NAME }}"
        sed -i '/variable "droplet_name" {/,/}/{s/^\(\s*default\s*=\s*"\).*\(".*\)/\1'"$droplet_name"'\2/}' variables.tf

        # Reemplazar el valor de default en la variable fingerprint_ssh_key_digitalocean del archivo variables.tf
        fingerprint_ssh_key_digitalocean="${{ env.FINGERPRINT_SSH_KEY_DIGITALOCEAN }}"
        sed -i '/variable "fingerprint_ssh_key_digitalocean" {/,/}/{s/^\(\s*default\s*=\s*"\).*\(".*\)/\1'"$fingerprint_ssh_key_digitalocean"'\2/}' variables.tf

    - name: Terraform Plan
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform plan

    - name: Create Droplet
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform apply -auto-approve

