# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NEURONE-Trivia CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.14.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Clonación de repositorio de Trivia
      uses: actions/checkout@v3
      with:
        path: trivia 
        
    # - name: Clonación de Neurone-gm
    #   uses: actions/checkout@v3
    #   with:
    #     repository: trabajo-titulacion-neurone/modulo-neurone-gm
    #     # token: 
    #     path: neurone-gm

    # - name: Clonación de Neurone-auth
    #   uses: actions/checkout@v3
    #   with:
    #     repository: NEURONE-IL/neurone-auth
    #     path: neurone-auth

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    #     cache-dependency-path: './trivia/Client/package-lock.json'
      
    # - name: Instalar MongoDB con Docker
    #   run: docker run -d --name mongo-for-tests -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=neuroneAdmin -e MONGO_INITDB_ROOT_PASSWORD=admin -e MONGO_INITDB_DATABASE=neuronegm mongo:latest
   
    # - name: Instalar pm2 globalmente
    #   run: npm install -g pm2
      
    # - name: Instalar http-server globalmente (OPCIONAL)
    #   run: npm install -g http-server

    # - name: Instalar Angular globalmente
    #   run: npm install -g @angular/cli
        
    # - name: Instalar Neurone-gm
    #   working-directory: ./neurone-gm/Server
    #   run: |
    #     npm install
    #     # npm test
    #     pm2 start app.js --name neurone-gm
    #     # timeout 2s pm2 logs

    # - name: Build Trivia Frontend
    #   working-directory: ./trivia/Client
    #   run: |
    #     ls
    #     npm install
    #     ng build --prod --output-path ../Server/public
        
    # - name: Instalar Trivia Backend
    #   working-directory: ./trivia/Server
    #   run: |
    #     npm install
    #     # npm test
    #     pm2 start app.js --name neurone-trivia
    #     # timeout 2s pm2 logs

    # - name: Run Frontend
    #   working-directory: ./trivia/Server/public
    #   run: nohup http-server -p 8080 &

    # - name: ls final
    #   run: pm2 ls

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

        
    - name: Create DigitalOcean Droplet
      run: doctl compute droplet create droplet-actions-neurone --image ubuntu-22-04-x64 --size s-1vcpu-1gb --region nyc1





