# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NEURONE-Trivia CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DROPLET_NAME: droplet-actions-neurone-v2 #Nombre que llevará el droplet a crear
  DROPLET_IPV4: "" #IPv4 que tendrá el droplet una vez creado
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }} #Clave publica de la maquina para conectarse al servidor
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}} #Clave privada de la maquina para conectarse al servidor
  SSH_KEY_ID: "" #ID que tendrá la clave publica agregada en el listado de claves de doctl
  SSH_KEY_NAME: key-droplet #Nombre que llevará la clave publica en doctl, se buscará si la clave existe de acuerdo con este nombre

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.14.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Clonación de repositorio de Trivia
      uses: actions/checkout@v3
      with:
        path: trivia 
        
    # - name: Clonación de Neurone-gm
    #   uses: actions/checkout@v3
    #   with:
    #     repository: trabajo-titulacion-neurone/modulo-neurone-gm
    #     # token: 
    #     path: neurone-gm

    # - name: Clonación de Neurone-auth
    #   uses: actions/checkout@v3
    #   with:
    #     repository: NEURONE-IL/neurone-auth
    #     path: neurone-auth

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    #     cache-dependency-path: './trivia/Client/package-lock.json'
      
    # - name: Instalar MongoDB con Docker
    #   run: docker run -d --name mongo-for-tests -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=neuroneAdmin -e MONGO_INITDB_ROOT_PASSWORD=admin -e MONGO_INITDB_DATABASE=neuronegm mongo:latest
   
    # - name: Instalar pm2 globalmente
    #   run: npm install -g pm2
      
    # - name: Instalar http-server globalmente (OPCIONAL)
    #   run: npm install -g http-server

    # - name: Instalar Angular globalmente
    #   run: npm install -g @angular/cli
        
    # - name: Instalar Neurone-gm
    #   working-directory: ./neurone-gm/Server
    #   run: |
    #     npm install
    #     # npm test
    #     pm2 start app.js --name neurone-gm
    #     # timeout 2s pm2 logs

    # - name: Build Trivia Frontend
    #   working-directory: ./trivia/Client
    #   run: |
    #     ls
    #     npm install
    #     ng build --prod --output-path ../Server/public
        
    # - name: Instalar Trivia Backend
    #   working-directory: ./trivia/Server
    #   run: |
    #     npm install
    #     # npm test
    #     pm2 start app.js --name neurone-trivia
    #     # timeout 2s pm2 logs

    # - name: Run Frontend
    #   working-directory: ./trivia/Server/public
    #   run: nohup http-server -p 8080 &

    # - name: ls final
    #   run: pm2 ls









    

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        

    #Se busca con doctl si existe o no una clave con el nombre $SSH_KEY_NAME en la cuenta de digitalocean, en caso de que no, la crea subiendo la clave publica $SSH_PUBLIC_KEY.
    - name: Find or upload ssh key for digitalocean account
      run: |
        # Si la clave SSH con nombre 'key-droplet' no existe, se crea.
        if ! doctl compute ssh-key list --format "Name" | grep -q $SSH_KEY_NAME; then
          echo "La clave SSH $SSH_KEY_NAME no se encontró. Creando nueva clave SSH..."
          doctl compute ssh-key create $SSH_KEY_NAME --public-key "$SSH_PUBLIC_KEY"
          echo "Clave SSH creada con éxito"
        #Sino, se imprime un mensaje por pantalla
        else
          echo "La clave SSH $SSH_KEY_NAME ya existe."
        fi
        #Se obtiene el ID de la clave para así agregarla al listado de claves permitidas del droplet a crear
        echo "SSH_KEY_ID=$(doctl compute ssh-key list --format "ID,Name" | grep $SSH_KEY_NAME | awk '{print $1}')" >> "$GITHUB_ENV"
        
    - name: print SSH_KEY_ID (BORRAR)
      run: echo "la key es $SSH_KEY_ID y el nombre de la clave es $SSH_KEY_NAME"
      
      
      
    #Se verifica si el droplet o VPS a crear ya existe (se busca por nombre)
    - name: Check if the Droplet exists
      run: |
        # Se obtiene el ID de un Droplet existente con nombre $DROPLET_NAME utilizando doctl y filtrando la salida con grep y awk.
        droplet_id=$(doctl compute droplet list --format "ID,Name" --no-header | grep $DROPLET_NAME | awk '{print $1}')
        
        if [[ -z $droplet_id ]]; then
          echo "Droplet does not exist" # Si el Droplet no existe, se imprime un mensaje
          echo "create_droplet=true" >> $GITHUB_ENV # Se establece una salida personalizada "create_droplet" en "true"
        else
          echo "Droplet already exists" # Si el Droplet ya existe, se imprime un mensaje
          echo "create_droplet=false" >> $GITHUB_ENV # Se establece una salida personalizada "create_droplet" en "false"
        fi
   
    # Si el droplet no existe, se crea.
    # Este paso se ejecutará solo si la salida personalizada "create_droplet" del paso anterior es 'true'
    - name: Create Droplet if it does not exist
      if: env.create_droplet == 'true'
      run: |
        #Se crea un nuevo droplet con las siguientes caracteristicas
        #Nombre: droplet-actions-neurone
        #SO: Ubuntu 22.04 x64 LTS
        #Region: Nueva York C1
        doctl compute droplet create $DROPLET_NAME --image ubuntu-22-04-x64 --size s-1vcpu-1gb --region nyc1 --ssh-keys $SSH_KEY_ID --wait

    #Se obtiene la IP del droplet con nombre DROPLET_NAME y se guarda en la variable de entorno DROPLET_IPV4
    - name: Get Public IPv4 address
      run: | 
        echo "DROPLET_IPV4=$(doctl compute droplet list --format "Name,Public IPv4" --no-header | grep $DROPLET_NAME | awk '{print $2}')" >> "$GITHUB_ENV"
        
        for i in {1..3}; do
          echo "Intento $i de conexión SSH"
          if ssh -o "StrictHostKeyChecking no" -i "$SSH_PRIVATE_KEY" root@${{ env.DROPLET_IPV4 }} 'echo "Conexión exitosa"'; then
            echo "Conexión exitosa"
            break
          fi
          echo "Conexión rechazada. Esperando y reintentando..."
          sleep 10  # Espera 10 segundos entre reintentos
        done
        if [ $i -eq 4 ]; then
          echo "Conexión SSH fallida después de 3 intentos."
          exit 1
        fi

        
    #Se realiza la conexión SSH con el servidor remoto creado
    - name: SSH Connection with Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.DROPLET_IPV4 }}
        username: root
        key: ${{ env.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "hola mundo estoy dentro del servidor"
          ls
          mkdir CarpetaSSH
 

