# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NEURONE-Trivia CI-CD

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]


env:
  #Dependencies Version
  NODE_VERSION: "10.19.0"
  ANGULAR_VERSION: "9.1.13"

  #SSH keys of Autorized Host to connect to pre-production server later
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }} #Clave publica de la maquina para conectarse al servidor
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}} #Clave privada de la maquina para conectarse al servidor
  #PASSPHRASE_SSH_PRIVATE_KEY: "frase-random" #DESCARTADO POR EL MOMENTO

  #NEURONEGM Database information
  NEURONEGM_DATABASE: "neuronegm"
  NEURONEGM_DATABASE_USER: "neuroneAdmin"
  NEURONEGM_DATABASE_PASSWORD: ${{ secrets.NEURONEGM_DATABASE_PASSWORD }}

  NEURONEGM_REPOSITORY: "trabajo-titulacion-neurone/modulo-neurone-gm"
  NEURONEGM_REPOSITORY_FOLDER_NAME: "neurone-gm"
  NEURONEGM_SERVER_DIRECTORY: "./neurone-gm/Server"

  #Trivia Data
  TRIVIA_REPOSITORY_FOLDER_NAME: "trivia"
  TRIVIA_CLIENT_DIRECTORY: "./trivia/Client"
  TRIVIA_SERVER_DIRECTORY: "./trivia/Server"
  BUILD_TRIVIA_LOCAL_PATH_SOURCE: "./trivia/Server/public"

  #Trivia deploy data
  NEURONE_DEPLOY_REPOSITORY: "trabajo-titulacion-neurone/neurone-deploy"
  NEURONE_DEPLOY_REPOSITORY_FOLDER_NAME: "neurone-deploy"
  TRIVIA_DEPLOY_DIRECTORY: "./neurone-deploy/trivia-deploy"
  TRIVIA_ANSIBLE_FILES_DIRECTORY: "./neurone-deploy/trivia-deploy/ansible-files"

  #Server Data
  SERVER_USERNAME: "gerardoluceroc"
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  SERVER_IPV4: 161.35.52.95
  SSH_PORT: 22
  BUILD_TRIVIA_SERVER_PATH_TARGET: "./apps/GAME/Server"


jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.14.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    #Generate a pair of SSH keys that will be replaced later by the environment variable keys
    - name: ssh-keygen
      run: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''

    - name: Copy ssh key of environment variables in local machine
      run: |
        echo "${{ env.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa  

        
      #ssh-keygen -p -P "" -N "${{ env.PASSPHRASE_SSH_PRIVATE_KEY }}" -f ~/.ssh/id_rsa

        
    - name: Cloning Trivia Repository
      uses: actions/checkout@v3
      with:
        path: ${{ env.TRIVIA_REPOSITORY_FOLDER_NAME }} 
        
    # - name: Cloning Neurone-gm repository
    #   uses: actions/checkout@v3
    #   with:
    #     repository: ${{ env.NEURONEGM_REPOSITORY }}
    #     # token: 
    #     path: ${{ env.NEURONEGM_REPOSITORY_FOLDER_NAME }}

    - name: Cloning neurone-deploy repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.NEURONE_DEPLOY_REPOSITORY }}
        # token: 
        path: ${{ env.NEURONE_DEPLOY_REPOSITORY_FOLDER_NAME }}

    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        # node-version: ${{ matrix.node-version }}
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.TRIVIA_CLIENT_DIRECTORY }}/package-lock.json'
      
    # - name: Run MongoDB with Docker
    #   run: docker run -d --name mongo-for-tests -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=${{ env.NEURONEGM_DATABASE_USER}} -e MONGO_INITDB_ROOT_PASSWORD=${{ env.NEURONEGM_DATABASE_PASSWORD }} -e MONGO_INITDB_DATABASE=${{ env.NEURONEGM_DATABASE }} mongo:latest
   
    # - name: Install pm2 globally
    #   run: npm install -g pm2
      
    # - name: Install http-server globally (OPTIONAL)
    #   run: npm install -g http-server

    - name: Install Angular globally
      run: npm install -g @angular/cli@${{env.ANGULAR_VERSION}}
        
    # - name: Run Neurone-gm Server with pm2
    #   working-directory: ${{ env.NEURONEGM_SERVER_DIRECTORY }}
    #   run: |
    #     npm install
    #     # npm test
    #     pm2 start app.js --name neurone-gm
    #     # timeout 2s pm2 logs

    # - name: Run Trivia Server with pm2
    #   working-directory: ${{ env.TRIVIA_SERVER_DIRECTORY }}
    #   run: |
    #     npm install
    #     # npm test
    #     pm2 start app.js --name neurone-trivia
    #     # timeout 2s pm2 logs

    # - name: Build Trivia Frontend
    #   working-directory: ${{ env.TRIVIA_CLIENT_DIRECTORY }}
    #   run: |
    #     npm install
    #     ng build --prod --output-path ../Server/public





    # - name: Deploy on server using Ansible with neurone-deploy repository
    #   uses: dawidd6/action-ansible-playbook@v2
    #   with:
    #     playbook: playbook.yaml # Required, playbook filepath
    #     directory: ${{ env.TRIVIA_ANSIBLE_FILES_DIRECTORY }} # Optional, directory where playbooks live
    #     key: ${{env.SSH_PRIVATE_KEY}} # Optional, SSH private key
    #     # The name of the inventory file is indicated
    #     options: |
    #       --inventory inventory.yaml


    - name: Se envía al servidor el build de trivia por ssh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ env.SERVER_IPV4 }}
        username: ${{ env.SERVER_USERNAME }}
        password: ${{ env.SERVER_PASSWORD }}
        # key: ${{ env.SSH_PRIVATE_KEY }}
        port: ${{ env.SSH_PORT }}
        source: ${{ env.BUILD_TRIVIA_LOCAL_PATH_SOURCE }}
        target: ${{ env.BUILD_TRIVIA_SERVER_PATH_TARGET }}
        strip_components: 3

        #key_path: /home/runner/.ssh/id_rsa
        #passphrase: ${{ env.PASSPHRASE_SSH_PRIVATE_KEY }}






























  

